include: package:flutter_lints/flutter.yaml

analyzer:
  # 注意：CI 与本地都要求先跑 build_runner，因此不需要为 *.g.dart 放宽规则
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - build/**

linter:
  rules:
    - always_declare_return_types
    - avoid_empty_else
    - avoid_print
    - cancel_subscriptions
    - close_sinks
    - directives_ordering
    - prefer_const_constructors
    - prefer_final_fields
    - prefer_single_quotes
    - sort_child_properties_last
    - unawaited_futures
    - use_build_context_synchronously
